"""added url to response

Revision ID: 6aaf8596092c
Revises: 1a8ed6b4afc9
Create Date: 2023-06-19 21:40:42.611001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aaf8596092c'
down_revision = '1a8ed6b4afc9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('url', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'url')
    # ### end Alembic commands ###
