"""changed ban property

Revision ID: a338b9e81849
Revises: 6aaf8596092c
Create Date: 2023-06-19 22:49:18.337619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a338b9e81849'
down_revision = '6aaf8596092c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('banned_at', sa.Boolean(), nullable=True))
    op.drop_column('api_keys', 'is_banned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('api_keys', 'banned_at')
    # ### end Alembic commands ###
